version: '3'


dotenv: [".env", '{{.ENV}}/.env.']

vars:
  BINDIR: .local/bin

  # Configuration Defaults
  NAMESPACE: rn
  RELEASE: rp
  HELM_OPTIONS: ""
  KIND_CLUSTERNAME: rp-helm

includes:
  tool:
    taskfile: tasks/ToolTasks.yaml
    vars:
      BINDIR: "{{.BINDIR}}"

# if a task is referenced multiple times, only run it once
run: once

tasks:

  up:
    cmds:
      - task: kind-create
      - task: install-redpanda-chart

  add-jetstack-repo:
    cmds:
      - helm repo add jetstack https://charts.jetstack.io
      - helm repo update
    status:
      - helm search repo -r '\vjetstack/cert-manager\v' | grep cert-manager

  install-cert-manager:
    deps:
      - add-jetstack-repo
    cmds:
      - helm upgrade --install cert-manager jetstack/cert-manager --set installCRDs=true --namespace cert-manager --create-namespace

  kind-create:
    cmds:
      - kind create cluster --name {{ .KIND_CLUSTERNAME }} --config ./.github/kind.yaml
      - task: install-cert-manager
    status:
      - "kind get clusters | grep {{ .KIND_CLUSTERNAME }}"

  kind-delete:
    cmds:
      - kind delete cluster --name {{ .KIND_CLUSTERNAME }}

  install-redpanda-chart:
    aliases:
      - upgrade-redpanda-chart
    cmds:
      - helm upgrade --install {{ .RELEASE }} ./charts/redpanda --namespace {{ .NAMESPACE }} --create-namespace --wait --debug {{ .HELM_OPTIONS }}

  uninstall-redpanda-chart:
    cmds:
      - helm uninstall {{ .RELEASE }} -n {{ .NAMESPACE }} --wait || true
      - kubectl -n {{ .NAMESPACE }} delete pods --all --grace-period=0 --force --wait=false || true
      - kubectl -n {{ .NAMESPACE }} delete pvc --all --force --grace-period=0 --wait=false || true
      - kubectl delete ns {{ .NAMESPACE }}

  minikube-start:
    cmds:
      - minikube start --nodes=4
      - kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.23/deploy/local-path-storage.yaml
      - ./scripts/change-default-sc.sh
      - task: install-cert-manager


  minikube-delete:
    cmds:
      - minikube delete
