---
# Default values for gke-cluster.

# nameOverride: ""
# fullNameOverride: ""

nodeCount: 4
# Make sure to use same Kubernetes version here as building the GCE image
kubernetesVersion: 1.23.3

# Name of the GCP datacenter location. Change this value to your desired location
region: "us-west1"
project: "my-project"
networkName: "default"
